apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: say-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: say
    spec:
      containers:
      - name: say
        image: gcr.io/demo24x7/say:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: gcr-json-key
---
kind: Service
apiVersion: v1
metadata:
  name: say-service
spec:
  selector: 
    app: say
  ports:
  - protocol: TCP
    port: 8080
  type: NodePort
  